### ISSUE TITLE
Lack of context propagation (traceid/spanid) in case of SQS queue (boto instrumentation)

### ISSUE THREAD

**Issue by mat-rumian** [aws-observability/aws-otel-python#11]
**Description**
In case of architecture:
* function A (AWS Lambda Python)
* SQS queue
* function B (AWS Lambda Python)

`Flow:`
1. Function A by **boto** library sends a message to SQS queue
2. Function B - trigger set as SQS queue and function makes a call to RDS (postgres)

`Both functions are auto instrumented by AWS ADOT Instrumentation deployed as Lambda layer`

**Expected behaviour:**
Only 1 trace with:
* client span related to sending message to SQS queue
* consumer span related to lambda hander method (function b)
* client span related to rds call 

**Current behaviour:**
There are two separated traces:
* First from `Function A` with a CLIENT span (sending message to SQS queue)
* Second from `Function B` but only with span related to RDS call

**Note:**
What I found is lack of `AWSTraceHeader` in SQS attributes for AWS OTEL Python Instrumentation. I believe this attribute is responsible for context propagation. 
When AWS X Ray is used as tracing then `AWSTraceHeader` is set.

**Comment by wangzlei** [comment]
Actually it caused by 2 problems: 
1. Lambda Function A does not propagate trace id to SQS, as you saw there is no AWSTraceHeader in SQS attribute. We have solved it in [opentelemetry-lambda](https://github.com/open-telemetry/opentelemetry-lambda), will sync to aws-otel-lambda soon.
2. Even SQS has AWSTraceHeader attribute, Lambda Function B still cannot propagate from that. Please refer details in thread https://github.com/aws/aws-xray-sdk-node/issues/208

**Comment by mat-rumian** [comment]
Tested newest version of the OTEL Python v1.5.
**Lambda code - sqs pusher:**
```
import boto3
import os

sqs = boto3.client('sqs', region_name="eu-central-1")
SQS_QUEUE_URL = os.getenv("SQS_QUEUE_URL")

def lambda_handler(event, context):
    response = sqs.send_message(
        QueueUrl=SQS_QUEUE_URL,
        DelaySeconds=10,
        MessageAttributes={
            'Title': {
                'DataType': 'String',
                'StringValue': 'The Whistler'
            },
        },
        MessageBody=(
            'Information about current NY Times fiction bestseller for '
            'week of 12/11/2016.'
        ),
    )

    print(response['MessageId'])

    return {'statusCode': 200, 'body': response['MessageId']}
```

**Lambda code - sqs puller**
```
from __future__ import print_function
import boto3

s3 = boto3.resource('s3')

def lambda_handler(event, context):
    for record in event['Records']:
        print("test")
        print(record)
        payload = record["body"]
        print(str(payload))
    # just to add some additional spans
    for bucket in s3.buckets.all():
        print(bucket)
```

**Env vars:**
![image](https://user-images.githubusercontent.com/58699800/131392834-549da9b5-6089-49aa-b418-2589b7ebfbbc.png)

**Result:**
`AWSTraceHeader` is not present in the MessageAttributes.

**IMPORTANT NOTE:**
In case of `sqs-pusher` I expect to see 2 spans: 
* root span from lambda handler method
* SQS push spans - this one is not generated but IMHO should be in the same way as call to S3 service
