### ISSUE TITLE
Add Prometheus Remote Write Exporter for Python SDK

### ISSUE THREAD

**Issue by alolita** [aws-observability/aws-otel-python#2]

**Comment by NathanielRN** [comment]
Hi @alolita, can we close this because we have https://github.com/open-telemetry/opentelemetry-python-contrib/tree/a3f60a65926fce2d2a1531aae7dfeb1a5961248c/exporter/opentelemetry-exporter-prometheus-remote-write merged upstream in OTel Python Contrib?

**Comment by vasireddy99** [comment]
The Prometheus remote write exporter now present in upstream [here](https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-prometheus). closing this issue.
